project_id = "yblkeicngnerkrtkolau"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[functions.create-razorpay-order]
verify_jwt = true