
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yblkeicngnerkrtkolau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlibGtlaWNuZ25lcmtydGtvbGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTY4NjEsImV4cCI6MjA2ODA3Mjg2MX0.O99R08r6Tdz6pNrNHmPrV5DZgbNfI2OyDOIXawvtA4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
